services:
  nginx:
    image: nginx:alpine
    container_name: sample-bg-nginx
    ports:
      - "8085:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  blue:
    image: traefik/whoami:latest
    container_name: sample-bg-blue
    profiles: ["blue"]
    ports:
      - "8081:80"

  green:
    image: traefik/whoami:latest
    container_name: sample-bg-green
    profiles: ["green"]
    ports:
      - "8082:80"
